### ISSUE TITLE
Copy (c) does not work on Linux

### ISSUE THREAD

**Issue by patrickbolle** [uschek/somafm#12]
Hitting the keyboard shortcut 'c' does not copy anything to the clipboard on Linux (Debian Stretch).

Fantastic app otherwise, thanks so much!

**Comment by patrickbolle** [comment]
Got it! Your copy-paste node plugin requires the installation of **xclip** on Linux. After installing xclip, the app copies the song title perfectly! Cheers! Maybe a good idea to add this to the readme perhaps?

**Comment by uschek** [comment]
Good catch, thanks! I added a note to the installation instructions in the readme. (3a7b07efaec5f9268fc50627d8ecc136f59366b7)

Glad you like the app. :)
