### ISSUE TITLE
Edit Favourites not saving

### ISSUE THREAD

**Issue by aswinramakrish** [uschek/somafm#6]
Hi,

First of all - Thanks a lot for this plugin. It's awesome!!

I noticed that when you edit the favorites list, it doesn't seem to be saving.

Here is what I did -

1. `somafm ef`
2. Copied the song from the cli - `Zanana Reflections - Ravi Chawla` and pasted it in the edit-favourites
3. Did `Esc` -> `:` -> `wq` to exit the file (Since it looked like `vim`).
4. It looked like it saved, but when I did `somafm lf`, I couldn't find the song and when I did `somafm ef`, my entry seemed to be missing.

Am I missing something?

**Comment by uschek** [comment]
Thanks a lot! :)

Favourites are saved in JSON format, containing a `favourites` attribute whose value is an array of strings. This way, other data like channel or timestamp could be added later.

When you add a song by pressing <kbd>+</kbd>, it is generated correctly, but running `$ somafm ef` with no contents creates a file with an empty JSON object (`{}`).

Try this to make it work:

```json
{
  "favourites": [
    "Zanana Reflections - Ravi Chawla"
  ]
}
```

**Comment by aswinramakrish** [comment]
I don't even know why I didn't think of that! 

Thanks
